Adopt a new way to write the log labels
Carbon-Fusion/lib-le-log pull request #6
Opened 2017-01-21 11:17 UTC by DevUt

2017-01-22 15:50 UTC, nailyk-fr requested changes
Good catches but need a bit of rework.

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> -#include <unistd.h>
Should be done into 461266350c80271865efb1ef616892d9cfbe25a1

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> -  // Write to kmsg if possibe.
Why removing comments?

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> +  char *warn = malloc(256);
What happens to the indent? 
(on every commits)

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> + char *buf = malloc(256);
ok: https://stackoverflow.com/questions/419022/char-x256-vs-char-malloc256sizeofchar/419029#419029
btw char buf[256]; could be better.

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> +    char *warn = malloc(256);
Ident problem here, as in every changes.

2017-01-22 15:50 UTC, nailyk-fr commented on C/kmsg_log.c
> +#include <unistd.h>
Ok on this commit.

2017-01-22 17:24 UTC, DevUt commented on C/kmsg_log.c
> +  char *warn = malloc(256);
On the github webview  the original code was written but this code is written in Atom and is presented it wisely and making me push it so I didn't get that difference

2017-01-22 17:25 UTC, DevUt commented on C/kmsg_log.c
> -  // Write to kmsg if possibe.
A briefing about what a function does is enough. We dont need to Comment everything , our code should be able to explain whats happening

Comment when you sense reader wont know whats happening

2017-01-23 20:57 UTC, nailyk-fr commented on C/kmsg_log.c
> -  // Write to kmsg if possibe.
Every lines are obscure for me :p 
So ok for this too.

2017-01-24 09:58 UTC, closed without merging