Adopt a new way to go with the loglevels
Carbon-Fusion/lib-le-log pull request #7
Opened 2017-01-24 10:45 UTC by DevUt

2017-01-25 18:19 UTC, nailyk-fr requested changes
Really hard to review. Patch is unreadable because of the indent problem. 
Your new version looks good except the indent.

2017-01-25 18:19 UTC, nailyk-fr commented on C/kmsg_log.c
> +    strcpy(buf,msg);
btw we still didn't check msg != NULL

2017-01-25 18:19 UTC, nailyk-fr commented on C/kmsg_log.c
> + char *warn = malloc(256);
Still bad indent :s

2017-01-25 18:19 UTC, nailyk-fr commented on C/kmsg_log.c
> +  free(warn);
Unreachable code

2017-01-25 18:19 UTC, nailyk-fr commented on C/kmsg_log.c
>    // Write to kmsg if possibe.
You didn't remove comments anymore?

2017-01-25 18:19 UTC, nailyk-fr commented on C/kmsg_log.c
> + char *debug = malloc(256);
Your are using malloc everywhere, good catch. 
But you set the same value on all entries. Can you use a preprocessor variable instead please?

2017-01-26 14:48 UTC, Rosalie241 approved these changes

2017-01-26 16:05 UTC, nailyk-fr reviewed
This one looks good, except the misplaced switch statement. 
Please, only for my happiness, can you rename tag --> buf?

2017-01-26 16:05 UTC, nailyk-fr commented on C/kmsg_log.c
> +    switch (level)
Switch misplaced, need to be out of the if(open())else statement.

2017-01-26 16:05 UTC, nailyk-fr commented on C/kmsg_log.c
> +      default : tag = "Error : Unknown log level "
Please two point: 
Make every log level same string lenght. (like ERR, WAR, INF)
I think you can import kernel log level too and assume default as max: 

case 7: 
default: 
    foo bar; 
    break;

2017-01-26 16:05 UTC, nailyk-fr commented on C/kmsg_log.c
> -	free(buf); // Empty buf memory.
no free(tag)?

2017-01-26 16:16 UTC, DevUt commented on C/kmsg_log.c
> +      default : tag = "Error : Unknown log level "
I didn't get the default point please elaborate

2017-01-26 16:17 UTC, DevUt commented on C/kmsg_log.c
> -	free(buf); // Empty buf memory.
Why free ? 
I used stack memory instead of heap 
I have no control on it (and its good) 
Its premanaged

2017-01-26 16:27 UTC, nailyk-fr commented on C/kmsg_log.c
> -	free(buf); // Empty buf memory.
Forget it. Yes and this way is way better!

2017-01-26 16:27 UTC, nailyk-fr commented on C/kmsg_log.c
> +      default : tag = "Error : Unknown log level "
Don't mind, will push them afterward.

2017-01-30 11:33 UTC, nailyk-fr commented on C/kmsg_log.c
> + int outbuf = open(DEFAULT_LOG_LOC, O_WRONLY);
Force define of DEFAULT_LOG_LOC in case not passed to makefile.

2017-01-30 11:33 UTC, nailyk-fr commented on C/Android.mk
> +	LOCAL_CFLAGS += -DDEFAULT_LOG_LOC=\"$(DEFAULT_LOG_LOC)\"
Add possibility to define ALT_LOG_LOC too.

2017-01-30 11:33 UTC, nailyk-fr approved these changes

2017-02-02 13:32 UTC, merged